[tool.black]
line-length = 80
target-version = ['py38']
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
# As this is `extend`, we already exclude everything in .gitignore.
^/(
  (
      frontend                 # don't bother looking through frontend
    | \.md$
    | \.txt$
    | \.ini$
    | LICENSE
    | \.toml$
    | backend/typings
  )
)
'''

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 80
